name: news_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_bottom_bar: ^2.0.0
  flutter_svg: 
  xml2json: ^5.3.5
  http: ^0.13.5
  
  cupertino_icons: ^1.0.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/categories/
    - assets/user.png
    - assets/cardimage.jpg
  fonts:
      - family: Times
        fonts:
          - asset: assets/fonts/times_news_roman/Times New Roman 400.ttf
            weight: 400
          - asset: assets/fonts/times_news_roman/Times New Roman Gras 700.ttf
            weight: 700
      - family: Avenir
        fonts:
          - asset: assets/fonts/avenir/AvenirNextLTPro-Regular.otf
            weight: 400
          - asset: assets/fonts/avenir/AvenirNextLTPro-Demi.otf
            weight: 500
          - asset: assets/fonts/avenir/AvenirNextLTPro-Demi.otf
            weight: 600
          - asset: assets/fonts/avenir/avenir-next-lt-pro-bold.otf
            weight: 700
      - family: League
        fonts:
          - asset: assets/fonts/league_spartan/LeagueSpartan-Bold.otf